### ISSUE TITLE
Wording in `test/action.yml` is confusing?

### ISSUE THREAD

**Issue by alessandrofelder** [neuroinformatics-unit/actions#21]
**Describe the bug**
In https://github.com/neuroinformatics-unit/actions/blob/main/test/action.yml we have an input variable called `use-xvfb` which is `false` by default. 

But IIUC (and I may well not!) in the [workflow steps sketched below:](https://github.com/neuroinformatics-unit/actions/blob/c0b8a6359300bf983d6cfa51a3e362b588cf05c1/test/action.yml#L41C1-L51C40) it looks to me like we are running the tests _with_ _XVFB_ (via aganders3/headless-gui@7084a2048d5f367f66a40f79b19bb3ca28248544) when `matrix.use-xvfb` is _False_
```
     - name: Run tests
      if: ${{ matrix.use-xvfb }}
      shell: bash
      run: tox ${{ inputs.tox-args }}

    - name: Run tests with XVFB
      if: ${{ !matrix.use-xvfb }}
      # SHA corresponds to v1.1 release
      uses: aganders3/headless-gui@7084a2048d5f367f66a40f79b19bb3ca28248544
      with:
        run: tox ${{ inputs.tox-args }}
```

**To Reproduce**
-

**Expected behaviour**
Tests should be run with XVFB when `use-xvfb` is `true`
