### ISSUE TITLE
Rethink use-xvb option in the test action

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/actions#50]
The test action currently accepts an optional "use-xvfb" argument, which in turn uses a headless-gui action (with a specific commit hash).
```yaml
- name: Run tests with XVFB
      if: ${{ matrix.use-xvfb }}
      # SHA corresponds to v1.1 release
      uses: aganders3/headless-gui@f85dd6316993505dfc5f21839d520ae440c84816
      with:
        run: tox ${{ inputs.tox-args }}
```

I'm not sure why this hash is needed, or if we can simply switch to v2 of that action.

We could also consider switching to the [https://github.com/pyvista/setup-headless-display-action](https://github.com/pyvista/setup-headless-display-action), which I think does the same (or similar) thing. @IgorTatarnikov has reported that it does the trick for `brainglobe-stitch`. We would have to compare that one to a more recent version of   `aganders3/headless-gui` and check which ones best serves our needs.
